package geolocation

import("bytes";"encoding/json";"net/http";"os";"path/filepath";"strconv";"sync";"time";"github.com/ArrowSK/ha-tkstar-gateway/internal/model")
type learned struct{Latitude float64 `json:"latitude"`;Longitude float64 `json:"longitude"`;Accuracy float64 `json:"accuracy"`;Samples int `json:"samples"`;Updated time.Time `json:"updated"`}
type Resolver struct{path,key string;mu sync.Mutex;cells map[string]learned;client *http.Client}
func New(root,key string)*Resolver{r:=&Resolver{path:filepath.Join(root,"cells.json"),key:key,cells:map[string]learned{},client:&http.Client{Timeout:8*time.Second}};b,_:=os.ReadFile(r.path);_=json.Unmarshal(b,&r.cells);return r}
func ck(c model.Cell)string{return strconv.Itoa(c.MCC)+"-"+strconv.Itoa(c.MNC)+"-"+strconv.Itoa(c.LAC)+"-"+strconv.Itoa(c.ID)}
func(r *Resolver)Learn(p model.Position){if !p.Valid||p.Latitude==0||p.Longitude==0{return};r.mu.Lock();defer r.mu.Unlock();changed:=false;for _,c:=range p.Cells{if c.ID<=0||c.LAC<=0{continue};k:=ck(c);v:=r.cells[k];n:=v.Samples;v.Latitude=(v.Latitude*float64(n)+p.Latitude)/float64(n+1);v.Longitude=(v.Longitude*float64(n)+p.Longitude)/float64(n+1);v.Samples=n+1;v.Updated=time.Now().UTC();if v.Accuracy==0{v.Accuracy=700};r.cells[k]=v;changed=true};if changed{r.save()}}
func(r *Resolver)Resolve(p *model.Position)bool{if p==nil||p.Valid||len(p.Cells)==0{return false};r.mu.Lock();var lat,lon,w,acc float64;for _,c:=range p.Cells{if v,ok:=r.cells[ck(c)];ok{ww:=1.0;lat+=v.Latitude*ww;lon+=v.Longitude*ww;w+=ww;if v.Accuracy>acc{acc=v.Accuracy}}};r.mu.Unlock();if w>0{p.Latitude=lat/w;p.Longitude=lon/w;p.Valid=true;p.Source="LBS_LOCAL";if acc<500{acc=500};p.Accuracy=acc;return true};if r.key!=""{return r.google(p)};return false}
func(r *Resolver)google(p *model.Position)bool{type tower struct{CellID int `json:"cellId"`;LocationAreaCode int `json:"locationAreaCode"`;MobileCountryCode int `json:"mobileCountryCode"`;MobileNetworkCode int `json:"mobileNetworkCode"`;SignalStrength int `json:"signalStrength,omitempty"`};req:=struct{RadioType string `json:"radioType"`;ConsiderIP bool `json:"considerIp"`;CellTowers[]tower `json:"cellTowers"`}{RadioType:"gsm",ConsiderIP:false};for _,c:=range p.Cells{req.CellTowers=append(req.CellTowers,tower{c.ID,c.LAC,c.MCC,c.MNC,c.Signal})};b,_:=json.Marshal(req);q,_:=http.NewRequest(http.MethodPost,"https://www.googleapis.com/geolocation/v1/geolocate?key="+r.key,bytes.NewReader(b));q.Header.Set("Content-Type","application/json");resp,e:=r.client.Do(q);if e!=nil{return false};defer resp.Body.Close();if resp.StatusCode/100!=2{return false};var out struct{Location struct{Lat float64 `json:"lat"`;Lng float64 `json:"lng"`} `json:"location"`;Accuracy float64 `json:"accuracy"`};if json.NewDecoder(resp.Body).Decode(&out)!=nil{return false};if out.Location.Lat==0&&out.Location.Lng==0{return false};p.Latitude=out.Location.Lat;p.Longitude=out.Location.Lng;p.Accuracy=out.Accuracy;p.Valid=true;p.Source="LBS_GOOGLE";r.mu.Lock();for _,c:=range p.Cells{r.cells[ck(c)]=learned{p.Latitude,p.Longitude,p.Accuracy,1,time.Now().UTC()}};r.save();r.mu.Unlock();return true}
func(r *Resolver)save(){b,e:=json.MarshalIndent(r.cells,"","  ");if e!=nil{return};tmp:=r.path+".tmp";if os.WriteFile(tmp,b,0600)==nil{_=os.Rename(tmp,r.path)}}
func(r *Resolver)Count()int{r.mu.Lock();defer r.mu.Unlock();return len(r.cells)}
