package store

import("bufio";"encoding/json";"errors";"math";"os";"path/filepath";"sort";"strings";"sync";"time";"github.com/ArrowSK/ha-tkstar-gateway/internal/model")
type Store struct{root string;retention int;mu sync.Mutex}
func New(root string,retention int)(*Store,error){if e:=os.MkdirAll(root,0750);e!=nil{return nil,e};return &Store{root:root,retention:retention},nil}
func(s *Store)LoadDevices()([]model.Device,error){s.mu.Lock();defer s.mu.Unlock();b,e:=os.ReadFile(filepath.Join(s.root,"devices.json"));if errors.Is(e,os.ErrNotExist){return nil,nil};if e!=nil{return nil,e};var d[]model.Device;e=json.Unmarshal(b,&d);return d,e}
func(s *Store)SaveDevices(d[]model.Device)error{s.mu.Lock();defer s.mu.Unlock();sort.Slice(d,func(i,j int)bool{return d[i].Name<d[j].Name});b,e:=json.MarshalIndent(d,"","  ");if e!=nil{return e};tmp:=filepath.Join(s.root,"devices.json.tmp");if e=os.WriteFile(tmp,b,0600);e!=nil{return e};return os.Rename(tmp,filepath.Join(s.root,"devices.json"))}
func safe(v string)string{var b strings.Builder;for _,r:=range v{if(r>='a'&&r<='z')||(r>='A'&&r<='Z')||(r>='0'&&r<='9')||r=='-'||r=='_'{b.WriteRune(r)}};if b.Len()==0{return"unknown"};return b.String()}
func(s *Store)AppendPosition(key string,p model.Position)error{day:=p.ReceivedAt.UTC().Format("2006-01-02");dir:=filepath.Join(s.root,"history",safe(key));if e:=os.MkdirAll(dir,0750);e!=nil{return e};return appendJSON(filepath.Join(dir,day+".jsonl"),p)}
func(s *Store)AppendAlarm(key string,p model.Position)error{day:=p.ReceivedAt.UTC().Format("2006-01-02");dir:=filepath.Join(s.root,"alarms",safe(key));if e:=os.MkdirAll(dir,0750);e!=nil{return e};return appendJSON(filepath.Join(dir,day+".jsonl"),p)}
func appendJSON(path string,v any)error{b,e:=json.Marshal(v);if e!=nil{return e};f,e:=os.OpenFile(path,os.O_CREATE|os.O_APPEND|os.O_WRONLY,0600);if e!=nil{return e};defer f.Close();_,e=f.Write(append(b,'\n'));return e}
func(s *Store)Positions(key string,from,to time.Time,max int)([]model.Position,error){if max<=0{max=5000};var out[]model.Position;for d:=dateOnly(from);!d.After(dateOnly(to));d=d.AddDate(0,0,1){_ = scan(filepath.Join(s.root,"history",safe(key),d.Format("2006-01-02")+".jsonl"),func(p model.Position){if !p.ReceivedAt.Before(from)&&!p.ReceivedAt.After(to){out=append(out,p)}})};if len(out)<=max{return out,nil};step:=float64(len(out)-1)/float64(max-1);sample:=make([]model.Position,0,max);for i:=0;i<max;i++{sample=append(sample,out[int(math.Round(float64(i)*step))])};return sample,nil}
func(s *Store)Alarms(key string,from,to time.Time,max int)([]model.Position,error){var out[]model.Position;for d:=dateOnly(from);!d.After(dateOnly(to));d=d.AddDate(0,0,1){_ = scan(filepath.Join(s.root,"alarms",safe(key),d.Format("2006-01-02")+".jsonl"),func(p model.Position){if p.Alarm!=""&&!p.ReceivedAt.Before(from)&&!p.ReceivedAt.After(to){out=append(out,p)}})};if max>0&&len(out)>max{out=out[len(out)-max:]};return out,nil}
func scan(path string,fn func(model.Position))error{f,e:=os.Open(path);if errors.Is(e,os.ErrNotExist){return nil};if e!=nil{return e};defer f.Close();sc:=bufio.NewScanner(f);sc.Buffer(make([]byte,64*1024),1024*1024);for sc.Scan(){var p model.Position;if json.Unmarshal(sc.Bytes(),&p)==nil{fn(p)}};return sc.Err()}
func dateOnly(t time.Time)time.Time{u:=t.UTC();return time.Date(u.Year(),u.Month(),u.Day(),0,0,0,0,time.UTC)}
func(s *Store)Cleanup(now time.Time)error{cut:=dateOnly(now.UTC().AddDate(0,0,-s.retention));for _,kind:=range[]string{"history","alarms"}{base:=filepath.Join(s.root,kind);ds,_:=os.ReadDir(base);for _,de:=range ds{if !de.IsDir(){continue};fs,_:=os.ReadDir(filepath.Join(base,de.Name()));for _,f:=range fs{if f.IsDir()||!strings.HasSuffix(f.Name(),".jsonl"){continue};d,e:=time.Parse("2006-01-02",strings.TrimSuffix(f.Name(),".jsonl"));if e==nil&&d.Before(cut){_=os.Remove(filepath.Join(base,de.Name(),f.Name()))}}}};return nil}
type Stats struct{Points int `json:"points"`;DistanceKm float64 `json:"distance_km"`;MaxSpeedKmh float64 `json:"max_speed_kmh"`;First time.Time `json:"first,omitempty"`;Last time.Time `json:"last,omitempty"`}
func ComputeStats(ps[]model.Position)Stats{var st Stats;var prev *model.Position;for i:=range ps{p:=ps[i];if !p.Valid{continue};st.Points++;if st.First.IsZero(){st.First=p.ReceivedAt};st.Last=p.ReceivedAt;if p.SpeedKmh>st.MaxSpeedKmh{st.MaxSpeedKmh=p.SpeedKmh};if prev!=nil&&p.ReceivedAt.Sub(prev.ReceivedAt)<=30*time.Minute{d:=haversine(prev.Latitude,prev.Longitude,p.Latitude,p.Longitude);if d<100{st.DistanceKm+=d}};q:=p;prev=&q};return st}
func haversine(a,b,c,d float64)float64{const r=6371.0;rad:=math.Pi/180;da:=(c-a)*rad;db:=(d-b)*rad;x:=math.Sin(da/2)*math.Sin(da/2)+math.Cos(a*rad)*math.Cos(c*rad)*math.Sin(db/2)*math.Sin(db/2);return 2*r*math.Atan2(math.Sqrt(x),math.Sqrt(1-x))}
