package gt06

import("bufio";"bytes";"context";"encoding/binary";"encoding/hex";"errors";"io";"log/slog";"net";"time";"github.com/ArrowSK/ha-tkstar-gateway/internal/model";"github.com/ArrowSK/ha-tkstar-gateway/internal/protocol")
const(login byte=0x01;location byte=0x12;status byte=0x13;alarm byte=0x16)
type Server struct{Addr string};func(s Server)Name()string{return"gt06"}
func(s Server)Run(ctx context.Context,sink protocol.Sink,log *slog.Logger)error{ln,e:=net.Listen("tcp",s.Addr);if e!=nil{return e};defer ln.Close();go func(){<-ctx.Done();_=ln.Close()}();log.Info("tracker listener started","protocol",s.Name(),"addr",s.Addr);for{c,e:=ln.Accept();if e!=nil{if ctx.Err()!=nil{return nil};return e};go handle(c,sink,log)}}
func handle(c net.Conn,sink protocol.Sink,log *slog.Logger){defer c.Close();r:=bufio.NewReaderSize(c,4096);device:="";for{_=c.SetReadDeadline(time.Now().Add(3*time.Minute));f,e:=readFrame(r);if e!=nil{return};if f.Protocol==login{device=hex.EncodeToString(f.Body);if !sink.Accept(device,"gt06"){return}};if device==""{continue};if f.Protocol==login||f.Protocol==status||f.Protocol==alarm{_,_=c.Write(ack(f.Protocol,f.Sequence))};m:=model.Message{DeviceID:device,Protocol:"gt06"};if f.Protocol==location||f.Protocol==alarm{p,e:=parseLocation(device,f.Body);if e!=nil{log.Debug("bad gt06 location","error",e);continue};if f.Protocol==alarm{p.Alarm="alarm";m.Alarm="alarm"};m.Position=p};sink.Handle(m)}}
type frame struct{Protocol byte;Body[]byte;Sequence uint16}
func readFrame(r *bufio.Reader)(frame,error){start:=make([]byte,2);if _,e:=io.ReadFull(r,start);e!=nil{return frame{},e};if !bytes.Equal(start,[]byte{0x78,0x78}){return frame{},errors.New("bad start")};l,e:=r.ReadByte();if e!=nil{return frame{},e};data:=make([]byte,int(l));if _,e=io.ReadFull(r,data);e!=nil{return frame{},e};stop:=make([]byte,2);if _,e=io.ReadFull(r,stop);e!=nil{return frame{},e};if !bytes.Equal(stop,[]byte{0x0d,0x0a}){return frame{},errors.New("bad stop")};if len(data)<5{return frame{},errors.New("short")};want:=binary.BigEndian.Uint16(data[len(data)-2:]);in:=append([]byte{l},data[:len(data)-2]...);if crc16(in)!=want{return frame{},errors.New("crc")};p:=data[0];seq:=binary.BigEndian.Uint16(data[len(data)-4:len(data)-2]);return frame{p,data[1:len(data)-4],seq},nil}
func parseLocation(id string,b[]byte)(*model.Position,error){if len(b)<18{return nil,errors.New("short location")};ts:=time.Date(2000+int(b[0]),time.Month(b[1]),int(b[2]),int(b[3]),int(b[4]),int(b[5]),0,time.UTC);q:=b[6];lat:=float64(binary.BigEndian.Uint32(b[7:11]))/30000/60;lon:=float64(binary.BigEndian.Uint32(b[11:15]))/30000/60;course:=binary.BigEndian.Uint16(b[16:18]);if course&0x400==0{lat=-lat};if course&0x800!=0{lon=-lon};valid:=course&0x1000!=0;p:=&model.Position{DeviceID:id,Timestamp:ts,ReceivedAt:time.Now().UTC(),Latitude:lat,Longitude:lon,Valid:valid,Source:"GPS",SpeedKmh:float64(b[15]),Heading:float64(course&0x03ff),Satellites:int(q&0x0f),Battery:-1,GSM:-1,Protocol:"gt06"};if !valid{p.Source="UNKNOWN";p.Latitude=0;p.Longitude=0};return p,nil}
func ack(proto byte,seq uint16)[]byte{b:=[]byte{0x05,proto,byte(seq>>8),byte(seq)};c:=crc16(b);return[]byte{0x78,0x78,0x05,proto,byte(seq>>8),byte(seq),byte(c>>8),byte(c),0x0d,0x0a}}
func crc16(data[]byte)uint16{crc:=uint16(0xffff);for _,b:=range data{crc^=uint16(b);for i:=0;i<8;i++{if crc&1!=0{crc=(crc>>1)^0x8408}else{crc>>=1}}};return ^crc}
