package h02

import("bufio";"context";"errors";"io";"log/slog";"net";"strconv";"strings";"time";"github.com/ArrowSK/ha-tkstar-gateway/internal/model";"github.com/ArrowSK/ha-tkstar-gateway/internal/protocol")
type Server struct{Addr string};func(s Server)Name()string{return "h02"}
func(s Server)Run(ctx context.Context,sink protocol.Sink,log *slog.Logger)error{ln,e:=net.Listen("tcp",s.Addr);if e!=nil{return e};defer ln.Close();go func(){<-ctx.Done();_=ln.Close()}();log.Info("tracker listener started","protocol",s.Name(),"addr",s.Addr);for{c,e:=ln.Accept();if e!=nil{if ctx.Err()!=nil{return nil};return e};go handle(c,sink,log)}}
func handle(c net.Conn,sink protocol.Sink,log *slog.Logger){defer c.Close();r:=bufio.NewReaderSize(c,4096);for{_=c.SetReadDeadline(time.Now().Add(3*time.Minute));raw,e:=r.ReadString('#');if e!=nil{if !errors.Is(e,io.EOF){log.Debug("h02 connection ended","error",e)};return};m,e:=Parse(strings.TrimSpace(raw));if e!=nil{log.Debug("unsupported h02 packet","error",e);continue};if !sink.Accept(m.DeviceID,"h02"){return};sink.Handle(m)}}
func Parse(raw string)(model.Message,error){if len(raw)<2||raw[0]!='*'||raw[len(raw)-1]!='#'{return model.Message{},errors.New("bad framing")};d:=strings.Split(raw[1:len(raw)-1],",");if len(d)<12||d[0]!="HQ"||d[2]!="V1"{return model.Message{},errors.New("unsupported packet")};p:=&model.Position{DeviceID:d[1],Protocol:"h02",ReceivedAt:time.Now().UTC(),Valid:strings.EqualFold(d[4],"A"),Source:"GPS",Battery:-1,GSM:-1};p.Timestamp,_=time.ParseInLocation("020106150405",d[11]+d[3],time.UTC);var e error;if p.Latitude,e=ddm(d[5],2,strings.EqualFold(d[6],"S"));e!=nil{return model.Message{},e};if p.Longitude,e=ddm(d[7],3,strings.EqualFold(d[8],"W"));e!=nil{return model.Message{},e};if v,x:=strconv.ParseFloat(d[9],64);x==nil{p.SpeedKmh=v*1.852};p.Heading,_=strconv.ParseFloat(d[10],64);var b *float64;if len(d)>17{if n,x:=strconv.Atoi(d[17]);x==nil{v:=battery(n);p.Battery=v;b=&v}};if !p.Valid{p.Source="UNKNOWN";p.Latitude=0;p.Longitude=0};return model.Message{DeviceID:d[1],Protocol:"h02",Position:p,Battery:b},nil}
func ddm(s string,n int,neg bool)(float64,error){if len(s)<=n{return 0,errors.New("invalid coordinate")};d,e:=strconv.ParseFloat(s[:n],64);if e!=nil{return 0,e};m,e:=strconv.ParseFloat(s[n:],64);if e!=nil{return 0,e};v:=d+m/60;if neg{v=-v};return v,nil}
func battery(n int)float64{switch{case n==0:return 0;case n<=3:return float64((n-1)*10);case n<=6:return float64((n-1)*20);case n<=100:return float64(n);case n>=0xF1&&n<=0xF6:return float64(n-0xF0)*20;default:return 0}}
